EmailBlaster/Controllers/CampaignController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using EmailBlaster.Models;
using EmailBlaster.ViewModels;
using EmailBlaster.Helpers;
using Microsoft.Ajax.Utilities;
using System.Threading;
using System.Threading.Tasks;

namespace EmailBlaster.Controllers
{
    public class CampaignController : Controller
    {
        private EmailBlasterContext db = new EmailBlasterContext();
        private string _sendgridapikey = Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
        private string _smtpUser = Environment.GetEnvironmentVariable("SENDGRID_SMTP_USER");
        private string _smtpPass = Environment.GetEnvironmentVariable("SENDGRID_SMTP_PASS");
        private int _emailbatchcount = Convert.ToInt32( ConfigurationManager.AppSettings["EmailBatchCount"]);

        // GET: Campaign
        public async Task< ActionResult> Index()
        {
            var model = await db.Campaigns.OrderByDescending(x => x.DateCreated).ToListAsync();

            return View(model);
        }

        // GET: Campaign/Create
        public ActionResult Create()
        {
            var model = new CampaignViewModel();

            return View(model);
        }

        // POST: Campaign/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Create([Bind(Exclude = "Id")] CampaignViewModel model)
        {
            if (ModelState.IsValid)
            {
                var o = new Campaign();

                // todo: use automapper here 
                o.Name = model.Campaign.Name;
                o.Sender = model.Campaign.Sender;
                o.Subject = model.Campaign.Subject;
                o.HtmlBody = model.Campaign.HtmlBody;
                o.TextBody = model.Campaign.TextBody;
                o.DateCreated = DateTime.Now;
                o.DateScheduled = model.Campaign.DateScheduled;

                db.Campaigns.Add(o);
                await db.SaveChangesAsync();

                TempData["SuccessMessage"] = "Campaign successfully created.";

                // use PRG(post redirect get) pattern
                return RedirectToAction("Edit", new {Id = o.Id});
            }
            else
            {
                return View(model);
            }
        }


        // GET: Campaign/Edit
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var model = new CampaignViewModel() {Campaign = db.Campaigns.SingleOrDefault(x => x.Id == id)};

            return View(model);
        }

        // POST: Campaign/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(CampaignViewModel model, string command)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // get existing campaign
                    var o = await db.Campaigns.SingleOrDefaultAsync(x => x.Id == model.Campaign.Id);

                    // todo: use automapper here 
                    o.Name = model.Campaign.Name;
                    o.Sender = model.Campaign.Sender;
                    o.Subject = model.Campaign.Subject;
                    o.HtmlBody = model.Campaign.HtmlBody;
                    o.TextBody = model.Campaign.TextBody;
                    o.DateScheduled = model.Campaign.DateScheduled;

                    // check which submit button was clicked
                    switch (command)
                    {
                        case "Send Test Email":
                            SendTestEmail(model, _sendgridapikey);
                            TempData["SuccessMessage"] = "Test email sent successfully.";
                            break;
                        case "Schedule Email":
                            TempData["SuccessMessage"] = "Email successfully  scheduled.";
                            break;
                        case "Save":
                            TempData["SuccessMessage"] = "Campaign saved successfully.";
                            break;
                        case "Send Now":
                            o.DateCreated = DateTime.Now;
                            SendCampaign(o);
                            TempData["SuccessMessage"] = "Campaign sent successfully.";
                            break;
                    }

                    await db.SaveChangesAsync();

                    return RedirectToAction("Edit", new {Id = o.Id});
                }
                else
                {
                    return View(model);
                }
            }
            catch (Exception)
            {
                throw;
            }

            return View(model);
        }

        private void SendTestEmail(CampaignViewModel  model, string apiKey)
        {
            EmailHelper.SendViaSmtpWithRetry(model.Campaign, model.SendTestEmail.Split(',',';'), _smtpUser, _smtpPass);
        }

        private void SendCampaign(Campaign campaign)
        {
            // get how many contacts
            double contactscount = db.Contacts.Count(x => x.Active == true);

            // get all 
            IQueryable<Contact> contacts = db.Contacts.Where(x => x.Active == true).OrderBy(x=>x.Email);

            int skip = 0;

            // loop through all subscribers, by batches of N
            while (contactscount > skip )
            {
                Debug.WriteLine("==========================");
                Debug.WriteLine(skip);
                Debug.WriteLine("==========================");

                IQueryable<Contact> _contacts = contacts.Skip(skip).Take(_emailbatchcount);

                string[] recipients = _contacts.Select(x => x.Email).ToArray();

                EmailHelper.SendViaSmtpWithRetry(campaign, recipients, _smtpUser, _smtpPass);

                // sleep for one second, SendGrid disallow more than 3K request per second
                Thread.Sleep(1000);

                skip += _emailbatchcount;
            }

            Debug.WriteLine("================================");
            Debug.WriteLine("Total Emails Sent: {counttotal}");
            Debug.WriteLine("================================");
        }


    }
}

EmailBlaster/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using EmailBlaster.Helpers;
using EmailBlaster.Models;
using EmailBlaster.Common;
using EmailBlaster.ViewModels;
using PagedList.EntityFramework;

namespace EmailBlaster.Controllers
{
    public class ContactController : Controller
    {
        private EmailBlasterContext db = new EmailBlasterContext();

        // GET: Contact
        public async Task<ActionResult> Index(string searchstring, int? page)
        {
            if (page == null) page = 1;

            // var contacts = from c in db.Contacts select c;
            var contacts = db.Contacts.Take(100);

            // filter
            if (!string.IsNullOrEmpty(searchstring))
            {
               contacts = contacts.Where(x => x.Email.Contains(searchstring));
            }

            // sort
            contacts = contacts.OrderBy(x => x.Email);

            return View(await contacts.OrderBy(x=>x.Email).ToPagedListAsync((int)page, 100));
        }

        // GET: Contact/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = await db.Contacts.FindAsync(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // GET: Contact/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contact/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Email,FirstName,LastName,Active,DateAdded,DateDeactivated,Unsubscribed,Bounced,MarkedSpam,InvalidMailbox")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Contacts.Add(contact);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(contact);
        }

        // GET: Contact/CreateBulk
        public ActionResult CreateBulk()
        {
            return View();
        }

        // POST: Contact/CreateBulk
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateBulk(HttpPostedFileBase upload)
        {
            try
            { 
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        // save uploaded file
                        string filename = Server.MapPath("~/Files/uploads/" + upload.FileName);
                        upload.SaveAs(filename);

                        // parse uploaded file into strongly typed contacts 
                        IEnumerable<Contact> contacts = FileHelper.ParseNewContacts(filename);

                        // exclude already existing emails
                        var newcontacts = contacts.Where(x => !db.Contacts.Any(y => y.Email == x.Email)).ToList();

                        // insert new contacts in db
                        db.Contacts.AddRange(newcontacts);
                        db.SaveChanges();

                        ViewBag.Message = string.Format("{0} contacts imported.", newcontacts.Count);
                    }
                }

                return View();
            }
            catch (Exception)
            {
                
                throw;
            }

            return View();
        }

        // GET: Contact/Unsubscribe
        public ActionResult Unsubscribe()
        {
            var model = new UnsubscribeViewModel();
                         
            return View(model);
        }

        // POST: Contact/Unsubscribe
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Unsubscribe(HttpPostedFileBase upload, int suppresionReason)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        // save uploaded file
                        string filename = Server.MapPath("~/Files/uploads/" + upload.FileName);
                        upload.SaveAs(filename);

                        // parse uploaded file into strongly typed contacts 
                        IEnumerable<Contact> contacts = FileHelper.ParseUnsubscribedContacts(filename);

                        // loop through all emails
                        int count = 0;
                        foreach (var contact in contacts)
                        {
                            var c = db.Contacts.SingleOrDefault(x => x.Email == contact.Email && x.Active==true);

                            if (c != null)
                            {
                                // set deactivated date to today
                                c.DateDeactivated = DateTime.Now;
                                c.Active = false;   

                                // assign reason for suppression
                                switch (suppresionReason)
                                {
                                    case (int)Enums.SuppressionReason.Unsubscribed:
                                        c.Unsubscribed = true;
                                        break;
                                    case (int)Enums.SuppressionReason.Bounced:
                                        c.Bounced = true;
                                        break;
                                    case (int)Enums.SuppressionReason.MarkedSpam:
                                        c.MarkedSpam = true;
                                        break;
                                    case (int)Enums.SuppressionReason.InvalidMailbox:
                                        c.InvalidMailbox = true;
                                        break;
                                    case (int)Enums.SuppressionReason.Blocked:
                                        c.Blocked = true;
                                        break;
                                }

                                // assign suppresion details
                                c.SuppressionReason = contact.SuppressionReason;

                                // commit changes to db
                                db.SaveChanges();

                                count++;
                            }
                        }
                        ViewBag.Message = string.Format("{0} contacts unsubscribed.", count);
                    }

                    var model = new UnsubscribeViewModel();

                    return View(model);
                }
            }
            catch (Exception)
            {

                throw;
            }

            return View();
        }

        // GET: Contact/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = await db.Contacts.FindAsync(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contact/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Email,FirstName,LastName,Active,DateAdded,DateDeactivated,Unsubscribed,Bounced,MarkedSpam,InvalidMailbox")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        // GET: Contact/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = await db.Contacts.FindAsync(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contact/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Contact contact = await db.Contacts.FindAsync(id);
            db.Contacts.Remove(contact);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EmailBlaster/Views/Shared/_CampaignEditor.cshtml
@using EmailBlaster.ViewModels
@model CampaignViewModel
@{
    ViewBag.Title = "Edit";
}
<div class="alert-success">@TempData["SuccessMessage"]</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.Campaign.Id)

    <div class="row">
        <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(m => m.Campaign.Name)
                    @Html.TextBoxFor(m => m.Campaign.Name, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Campaign.Sender)
                    @Html.TextBoxFor(m => m.Campaign.Sender, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Campaign.Subject)
                    @Html.TextBoxFor(m => m.Campaign.Subject, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.SendTestEmail)
                    @Html.TextBoxFor(m => m.SendTestEmail, new { @class = "form-control" })
                    <input type="submit" class="btn btn-default" value="Send Test Email" name="command" />
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Campaign.DateScheduled)
                    @Html.TextBoxFor(m => m.Campaign.DateScheduled, new { @class = "form-control" })
                    <input type="submit" class="btn btn-default" value="Schedule Email" name="command" />
                </div>
            <hr />
                <div class="form-group">
                    <input type="submit" class="btn btn-block btn-primary " value="Save" name="command" />
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-block btn-danger" value="Send Now" name="command" />
                </div>
        </div>
        <div class="col-md-9">
            <div class="row">
                @Html.LabelFor(m => m.Campaign.HtmlBody)
                @Html.TextAreaFor(m => m.Campaign.HtmlBody, new { @class="" })
            </div>
            <div class="row">
                @Html.LabelFor(m => m.Campaign.TextBody)<br />
                @Html.TextAreaFor(m => m.Campaign.TextBody, new { @rows = "4", @style= " max-width: 100%;width: 100%;" })
            </div>
        </div>
    </div>
}

EmailBlaster/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Email Blaster</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("css", required:false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Email Blaster", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contacts", "Index", "Contact")</li>
                    <li>@Html.ActionLink("Campaigns", "Index", "Campaign")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Email Blaster/p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
</body>
</html>